### ISSUE TITLE
Rework not finding @custom-media in the parser

### ISSUE THREAD

**Issue by SlexAxton** [reworkcss/rework-custom-media#1]
It's just treating them like selectors :/

``` js
type: 'rule',
  selectors: [ '@custom-media --medium-window screen and (min-width:600px);\n\n.grid' ]
```

With rework 1.0.0. This repo's tests work though. So I have no idea. Wondering if you have any clues?

**Comment by SlexAxton** [comment]
Nevermind, I have rework updated, but broccoli rework is still on the old one. Sorry. (Though maybe it should note that this only works with rework 1+)

**Comment by necolas** [comment]
Thanks. Added a note in the first line of the README.
