### ISSUE TITLE
Variables not working

### ISSUE THREAD

**Issue by jasonkuhrt** [reworkcss/rework-custom-media#3]
Definition like:

```
@custom-media --md-viewport screen and (min-width: var(--max-row-width));
```

Results in:

```
@media screen and (min-width: var(--max-row-width)) {
  .ViewDashboard {
    color: red!important;
  }
}
```

I do not see any community examples using `--var` so curious if this is a known limitation. Seems highly limiting though, so would be weird.

**Comment by conradz** [comment]
This is an issue in rework-vars, I filed a bug in rework-css/rework-vars#31.

**Comment by conradz** [comment]
@jasonkuhrt at least I'm supposing you're using rework-vars (I reread and realized it doesn't explicitly say). Reopen if you think it's something different.

**Comment by jasonkuhrt** [comment]
@conradz Nope that's it. Thanks for the redirection.

**Comment by jasonkuhrt** [comment]
@conradz Oh wait, this issue is about `--var()` _within_ the `@custom-media` declaration, **_not**_ the `@media` declaration. Therefore, I am not certain https://github.com/reworkcss/rework-vars/issues/31 is the same issue. It may well be, but please confirm.

**Comment by jasonkuhrt** [comment]
@conradz I think the confusion stems from my incomplete example, please review this one instead:

Source code:

``` css
@custom-media --md-viewport screen and (min-width: var(--max-row-width));
@media (--md-viewport) {
  ...
}
```

myth.io processing output:

``` css
@media screen and (min-width: var(--max-row-width)) {
  ...
}

```

/cc @necolas

**Comment by MoOx** [comment]
The specs said

> The var() function can be used in place of any part of a value in any property on an element.

A media query is not an element.
I don't see the point about using a var() here. You can redefine the `@custom-media` like you can override a property (or a custom property)

**Comment by jasonkuhrt** [comment]
@MoOx Thanks for clearing this up.

> I don't see the point about using a var() here. You can redefine the @custom-media like you can override a property (or a custom property)

Typography, informs grid, informs breakpoints. Maintaining breakpoint values apart from base typography makes little sense I think.

**Comment by MoOx** [comment]
I'm not sur maintaing a breakpoint is very different from maintaining a entire property.

``` css
/* defined in a lib */
:root {
  --max-row-width: 50em;
}
@custom-media --md-viewport screen and (min-width: var(--max-row-width));
/* ... */

/* used somewhere */
@media (--md-viewport) { /* ... */ }

/* ... */

/* change from the lib*/
:root {
  --max-row-width: 54em;
}
```

I think this should works (according to the specs)

``` css
/* defined in a lib */
@custom-media --md-viewport screen and (min-width: 50em);
/* ... */

/* used somewhere */
@media (--md-viewport) { /* ... */ }

/* ... */

/* change from the lib*/
@custom-media --md-viewport screen and (min-width: 54em);
```

**Comment by MoOx** [comment]
From http://www.w3.org/TR/css3-mediaqueries/#media1

> Syntactically, media features resemble CSS properties: they have names and accept certain values. There are, however, several important differences between properties and media features:
> 
> Properties are used in declarations to give information about how to present a document. Media features are used in expressions to describe requirements of the output device. 
> 
> ...
> 
> **Properties may accept more complex values, e.g., calculations that involve several other values. Media features only accept single values**: one keyword, one number, or a number with a unit identifier. (The only exceptions are the ‘aspect-ratio’ and ‘device-aspect-ratio’ media features.)

Maybe try to ask @tabatkins about that or try w3c mailing list to get more accurate explanation.

**Comment by jasonkuhrt** [comment]
@MoOx Why would you change `--md-viewport` once you've defined it once? Also, is that even possible?? So you're saying the output could e.g. be:

```
@media screen and (min-width: 50em) { /* ... */ }


... later on in the codebase ...


@media screen and (min-width: 54em) { /* ... */ }
```

I thought custom-media was global like vars and that changing them anywhere in the codebase updates all where they are used. No?

**Comment by MoOx** [comment]
CSS are supposed to be dynamic so yes, overriding a definition should affect all "previous" definitions.

I'm guessing it's should be the same as it is for vars

https://github.com/reworkcss/rework-vars/blob/master/test/fixtures/substitution-overwrite.css
https://github.com/reworkcss/rework-vars/blob/master/test/fixtures/substitution-overwrite.out.css

**Comment by jasonkuhrt** [comment]
@MoOx That's what I thought, the override is applied globally and retroactively, its last-one-wins for the whole codebase. You had me thinking that up-until-the-override css would output with the previous value which is not the case.

**Comment by tabatkins** [comment]
You're right that redefining a `@custom-media` is possible, and the last one wins for all references.

You can't use `var()` in a `@custom-media`, as there's no element to get its value from.

**Comment by jasonkuhrt** [comment]
> You can't use var() in a @custom-media, as there's no element to get its value from.

@tabatkins I understand the premise that fundamentally `@custom-media` is not a property etc.

I'm just curious if you think the end result of managing typography dynamics apart from breakpoint dynamics makes good sense. As I stated above I think: Typography, informs grid, informs breakpoints.

Keeping in mind that `@custom-media` is not a property, would there be any other _plausible_ solution from your POV (near or far future).

Its not a big deal to keep `@custom-media` nearby `--var-base-leading: ...` etc. so that manual verification is easier but I'm not 100% sure that these dynamics will always have the privilege of being so spatially close in a codebase. It also makes responsive grid libraries harder to consume downstream if users want to fiddle with the variables etc.

**Comment by tabatkins** [comment]
I think it makes sense to introduce some form of "global variable" that can apply equally to properties and other things.  `var()` just isn't it (yet).

**Comment by jasonkuhrt** [comment]
@tabatkins cool thanks for sharing
